#!/bin/bash
# Guide for Getting AWS Credentials

export PATH="/opt/homebrew/bin:$PATH"

echo "🔑 Getting AWS Access Key ID and Secret Access Key"
echo "=================================================="
echo ""
echo "Step 1: Sign in to AWS Console"
echo "   Go to: https://console.aws.amazon.com/"
echo "   Sign in with email: etweinhaus@gmail.com"
echo ""
echo "Step 2: Navigate to Security Credentials"
echo "   - Click on your account name (top right)"
echo "   - Click 'Security credentials'"
echo "   OR go directly to:"
echo "   https://console.aws.amazon.com/iam/home#/security_credentials"
echo ""
echo "Step 3: Create Access Key"
echo "   - Scroll down to 'Access keys' section"
echo "   - Click 'Create access key'"
echo "   - Select 'Command Line Interface (CLI)' as use case"
echo "   - Click 'Next' and 'Create access key'"
echo "   - IMPORTANT: Copy both:"
echo "     • Access Key ID (starts with AKIA...)"
echo "     • Secret Access Key (long string)"
echo "   - Save these securely - Secret Access Key is shown only once!"
echo ""
echo "Step 4: Configure AWS CLI"
echo "   Run this command:"
echo "   aws configure"
echo ""
echo "   Then enter:"
echo "   - AWS Access Key ID: [paste your Access Key ID]"
echo "   - AWS Secret Access Key: [paste your Secret Access Key]"
echo "   - Default region name: us-east-1"
echo "   - Default output format: json"
echo ""
echo "Alternative: Set Environment Variables"
echo "   export AWS_ACCESS_KEY_ID=your_access_key_id"
echo "   export AWS_SECRET_ACCESS_KEY=your_secret_access_key"
echo "   export AWS_DEFAULT_REGION=us-east-1"
echo ""
echo "After configuring, run: ./check_prerequisites.sh"

