"""Initial schema: create all tables

Revision ID: c34e4fefa31d
Revises: 
Create Date: 2025-11-03 21:22:45.661901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34e4fefa31d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_tutors_created_at', 'tutors', ['created_at'], unique=False)
    op.create_index('ix_tutors_email', 'tutors', ['email'], unique=False)
    op.create_table('sessions',
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('rescheduled', 'no_show') AND completed_time IS NULL) OR (status = 'completed')", name='check_completed_time_null'),
    sa.CheckConstraint("status IN ('completed', 'rescheduled', 'no_show')", name='check_status'),
    sa.CheckConstraint('completed_time IS NULL OR completed_time >= scheduled_time', name='check_time_order'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_scheduled_time', 'sessions', ['scheduled_time'], unique=False)
    op.create_index('ix_sessions_status', 'sessions', ['status'], unique=False)
    op.create_index('ix_sessions_tutor_id', 'sessions', ['tutor_id'], unique=False)
    op.create_index('ix_sessions_tutor_scheduled', 'sessions', ['tutor_id', 'scheduled_time'], unique=False)
    op.create_table('tutor_scores',
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.Column('reschedule_rate_7d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reschedule_rate_30d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reschedule_rate_90d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_sessions_7d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sessions_30d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sessions_90d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tutor_reschedules_7d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tutor_reschedules_30d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tutor_reschedules_90d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_high_risk', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('risk_threshold', sa.Numeric(precision=5, scale=2), server_default='15.00', nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_high_risk = false) OR (reschedule_rate_7d > risk_threshold OR reschedule_rate_30d > risk_threshold OR reschedule_rate_90d > risk_threshold)', name='check_risk_flag'),
    sa.CheckConstraint('reschedule_rate_30d IS NULL OR (reschedule_rate_30d >= 0 AND reschedule_rate_30d <= 100)', name='check_rate_30d'),
    sa.CheckConstraint('reschedule_rate_7d IS NULL OR (reschedule_rate_7d >= 0 AND reschedule_rate_7d <= 100)', name='check_rate_7d'),
    sa.CheckConstraint('reschedule_rate_90d IS NULL OR (reschedule_rate_90d >= 0 AND reschedule_rate_90d <= 100)', name='check_rate_90d'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_index('ix_tutor_scores_is_high_risk', 'tutor_scores', ['is_high_risk'], unique=False)
    op.create_index('ix_tutor_scores_last_calculated_at', 'tutor_scores', ['last_calculated_at'], unique=False)
    op.create_index('ix_tutor_scores_tutor_id', 'tutor_scores', ['tutor_id'], unique=False)
    op.create_table('email_reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    # Note: No updated_at field per PRD specification
    sa.CheckConstraint("status IN ('sent', 'failed', 'pending')", name='check_email_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_reports_sent_at', 'email_reports', ['sent_at'], unique=False)
    op.create_index('ix_email_reports_session_id', 'email_reports', ['session_id'], unique=False)
    op.create_index('ix_email_reports_status', 'email_reports', ['status'], unique=False)
    op.create_table('reschedules',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('initiator', sa.String(length=50), nullable=False),
    sa.Column('original_time', sa.DateTime(), nullable=False),
    sa.Column('new_time', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=False),
    sa.Column('hours_before_session', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    # Note: No updated_at field per PRD specification
    sa.CheckConstraint("initiator IN ('tutor', 'student')", name='check_initiator'),
    sa.CheckConstraint('new_time IS NULL OR new_time > original_time', name='check_new_time'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_reschedules_cancelled_at', 'reschedules', ['cancelled_at'], unique=False)
    op.create_index('ix_reschedules_initiator', 'reschedules', ['initiator'], unique=False)
    op.create_index('ix_reschedules_reason_code', 'reschedules', ['reason_code'], unique=False)
    op.create_index('ix_reschedules_session_id', 'reschedules', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reschedules_session_id', table_name='reschedules')
    op.drop_index('ix_reschedules_reason_code', table_name='reschedules')
    op.drop_index('ix_reschedules_initiator', table_name='reschedules')
    op.drop_index('ix_reschedules_cancelled_at', table_name='reschedules')
    op.drop_table('reschedules')
    op.drop_index('ix_email_reports_status', table_name='email_reports')
    op.drop_index('ix_email_reports_session_id', table_name='email_reports')
    op.drop_index('ix_email_reports_sent_at', table_name='email_reports')
    op.drop_table('email_reports')
    op.drop_index('ix_tutor_scores_tutor_id', table_name='tutor_scores')
    op.drop_index('ix_tutor_scores_last_calculated_at', table_name='tutor_scores')
    op.drop_index('ix_tutor_scores_is_high_risk', table_name='tutor_scores')
    op.drop_table('tutor_scores')
    op.drop_index('ix_sessions_tutor_scheduled', table_name='sessions')
    op.drop_index('ix_sessions_tutor_id', table_name='sessions')
    op.drop_index('ix_sessions_status', table_name='sessions')
    op.drop_index('ix_sessions_scheduled_time', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_tutors_email', table_name='tutors')
    op.drop_index('ix_tutors_created_at', table_name='tutors')
    op.drop_table('tutors')
    # ### end Alembic commands ###
